package javaapplication1;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sunny
 */
public class Student extends javax.swing.JInternalFrame {

    /**
     * Creates new form px1
     */
    public Student() {
        initComponents();
         setResizable(true);
        setMaximizable(true);
        setIconifiable(true);
        setClosable(true);
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtRollNo = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtMarks = new javax.swing.JTextField();
        cmbCountry = new javax.swing.JComboBox();
        btnModify = new javax.swing.JButton();
        btnModify1 = new javax.swing.JButton();
        btnSave1 = new javax.swing.JButton();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Title1");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 510, 650));

        txtRollNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRollNoActionPerformed(evt);
            }
        });
        getContentPane().add(txtRollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 280, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 280, -1));

        txtMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarksActionPerformed(evt);
            }
        });
        getContentPane().add(txtMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 280, -1));

        cmbCountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "India", "Canada", "USA", "Japan" }));
        getContentPane().add(cmbCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 280, -1));

        btnModify.setText("Delete");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        getContentPane().add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, -1, -1));

        btnModify1.setText("Modify");
        btnModify1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModify1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnModify1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, -1));

        btnSave1.setText("Save");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        buttonGroup1.add(rbMale);
        rbMale.setSelected(true);
        rbMale.setText("Male");
        rbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaleActionPerformed(evt);
            }
        });
        getContentPane().add(rbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        buttonGroup1.add(rbFemale);
        rbFemale.setText("Female");
        getContentPane().add(rbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jLabel5.setText("Country");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel3.setText("Marks");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 40, -1));

        jLabel1.setText("Roll No");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        TableModel k1 = jTable1.getModel();
        String rollno = (String) k1.getValueAt(row, 0);
        String name = (String) k1.getValueAt(row, 1);
        String marks = (String) k1.getValueAt(row, 2);
        String gender = (String) k1.getValueAt(row, 3);
        String country = (String) k1.getValueAt(row, 4);

        txtRollNo.setText(rollno);
        txtName.setText(name);
        txtMarks.setText(marks);
        if (gender.equalsIgnoreCase("male")) {
            rbMale.setSelected(true);
        } else {
            rbFemale.setSelected(true);
        }

        cmbCountry.setSelectedItem(country);
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtRollNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRollNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRollNoActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
        deleteData();
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnModify1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModify1ActionPerformed
        // TODO add your handling code here:
        modifyData();
    }//GEN-LAST:event_btnModify1ActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        // TODO add your handling code here:
        saveData();
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMaleActionPerformed

    private void txtMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarksActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed
 
    void showData() {

        try {

            Vector h = new Vector();
            h.add("Roll");
            h.add("Name");
            h.add("Marks");
            h.add("Gender");
            h.add("Country");

            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "uday", "12345");
            String q = "select * from student";
            PreparedStatement y = x.prepareStatement(q);
            ResultSet rs = y.executeQuery();

            Vector d = new Vector();

            String rollno, name, marks, gender, country;
            while (rs.next()) {
                rollno = rs.getString("rollno");
                name = rs.getString("name");
                marks = rs.getString("marks");
                gender = rs.getString("gender");
                country = rs.getString("country");

                Vector r = new Vector();
                r.add(rollno);
                r.add(name);
                r.add(marks);
                r.add(gender);
                r.add(country);

                //inserted into data
                d.add(r);
            }
            y.close();
            x.close();

            DefaultTableModel z = new DefaultTableModel(d, h);
            jTable1.setModel(z);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
            ex.printStackTrace();
        }

    }

    void saveData() {
        try {
            String name, rollno, marks, gender, country;
            rollno = txtRollNo.getText();
            name = txtName.getText();
            marks = txtMarks.getText();

            if (rbMale.isSelected()) {
                gender = "male";
            } else {
                gender = "female";
            }

            country = (String) cmbCountry.getSelectedItem();

            if (rollno.trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "Roll Number cannot be empty");
                return;
            }

            if (name.trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "Name cannot be empty");
                return;
            }

            if (marks.trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "Marks cannot be empty");
                return;
            }

            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "jp20192", "123456");

            String q = "insert into student values(?,?,?,?,?)";

            PreparedStatement y = x.prepareStatement(q);

            y.setString(1, rollno);
            y.setString(2, name);
            y.setString(3, marks);
            y.setString(4, gender);
            y.setString(5, country);

            int n = y.executeUpdate();
            String d = n + " data inserted";

            y.close();

            x.close();

            JOptionPane.showMessageDialog(this, d);

            showData();
            clearData();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());

            ex.printStackTrace();
        }
    }

    void modifyData() {
        try {
            String name, rollno, marks, gender, country;
            rollno = txtRollNo.getText();
            name = txtName.getText();
            marks = txtMarks.getText();

            if (rbMale.isSelected()) {
                gender = "male";
            } else {
                gender = "female";
            }

            country = (String) cmbCountry.getSelectedItem();

            if (rollno.trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "Roll Number cannot be empty");
                return;
            }

            if (name.trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "Name cannot be empty");
                return;
            }

            if (marks.trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "Marks cannot be empty");
                return;
            }

            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "jp20192", "123456");

            String q = "update student set name=?,marks=?,gender=?,country=? where rollno=?";

            PreparedStatement y = x.prepareStatement(q);

            y.setString(1, name);
            y.setString(2, marks);
            y.setString(3, gender);
            y.setString(4, country);
            y.setString(5, rollno);

            int n = y.executeUpdate();
            String d = n + " data updated";

            y.close();

            x.close();

            JOptionPane.showMessageDialog(this, d);

            showData();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());

            ex.printStackTrace();
        }
    }

    void deleteData() {
        try {
            String rollno;
            rollno = txtRollNo.getText();

            if (rollno.trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "Roll Number cannot be empty");
                return;
            }

            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "jp20192", "123456");

            String q = "delete from student where rollno=?";

            PreparedStatement y = x.prepareStatement(q);

            y.setString(1, rollno);

            int n = y.executeUpdate();
            String d = n + " data deleted";

            y.close();

            x.close();

            JOptionPane.showMessageDialog(this, d);

            showData();
            clearData();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());

            ex.printStackTrace();
        }
    }

    void clearData() {
        txtRollNo.setText("");
        txtName.setText("");
        txtMarks.setText("");
        rbMale.setSelected(true);
        cmbCountry.setSelectedIndex(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnModify1;
    private javax.swing.JButton btnSave1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbCountry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextField txtMarks;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRollNo;
    // End of variables declaration//GEN-END:variables
}
