/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author project mahajan
 */
public class EditEmployee extends javax.swing.JInternalFrame {

    /**
     * Creates new form student
     */
    public EditEmployee() {
        initComponents();
        setResizable(true);
        setMaximizable(true);
        setIconifiable(true);
        setClosable(true);
        showData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        empid = new javax.swing.JLabel();
        txteid = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        rbmale = new javax.swing.JRadioButton();
        rbfemale = new javax.swing.JRadioButton();
        salary = new javax.swing.JLabel();
        txtsal = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtadd = new javax.swing.JTextArea();
        designation = new javax.swing.JLabel();
        idesignation = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        Delete = new javax.swing.JButton();
        save = new javax.swing.JButton();
        modify = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txthire = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcontact = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbsingle = new javax.swing.JRadioButton();
        rbmarried = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtdob = new javax.swing.JTextField();
        user = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        pwd = new javax.swing.JLabel();
        txtpwd = new javax.swing.JPasswordField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empid.setText("EmpId");
        getContentPane().add(empid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 20));
        getContentPane().add(txteid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 110, -1));

        name.setText("Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 20));
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 110, -1));

        gender.setText("Gender");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        buttonGroup1.add(rbmale);
        rbmale.setText("Male");
        getContentPane().add(rbmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        buttonGroup1.add(rbfemale);
        rbfemale.setText("Female");
        getContentPane().add(rbfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        salary.setText("Salary");
        getContentPane().add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));
        getContentPane().add(txtsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 110, -1));

        address.setText("Address");
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        txtadd.setColumns(20);
        txtadd.setRows(5);
        jScrollPane1.setViewportView(txtadd);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 210, 90));

        designation.setText("Designation");
        getContentPane().add(designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        idesignation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Project Manager", "Team Leader", "Team Member" }));
        getContentPane().add(idesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 710, 450));

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, -1, -1));

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        modify.setText("Modify");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });
        getContentPane().add(modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, -1, -1));

        jLabel1.setText("Hire Date");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));
        getContentPane().add(txthire, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 110, -1));

        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 210, -1));

        jLabel3.setText("Contact No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));
        getContentPane().add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 140, -1));

        jLabel4.setText("Marital Status");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, -1));

        buttonGroup2.add(rbsingle);
        rbsingle.setText("Single");
        getContentPane().add(rbsingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, -1, -1));

        buttonGroup2.add(rbmarried);
        rbmarried.setText("Married");
        rbmarried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmarriedActionPerformed(evt);
            }
        });
        getContentPane().add(rbmarried, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 90, -1, -1));

        jLabel5.setText("Date of Birth");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, -1, -1));

        txtdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdobActionPerformed(evt);
            }
        });
        getContentPane().add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 150, -1));

        user.setText("Username");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 140, -1));

        pwd.setText("Password");
        getContentPane().add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, -1, -1));
        getContentPane().add(txtpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        deleteData();
    }

    private void btnModify1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        modifyData();
    }

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        saveData();
    }

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtMarksActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code hint row = table.getSelectedRow();
        TableModel z = table.getModel();

        int row = table.getSelectedRow();
        String eid = (String) z.getValueAt(row, 0);
        String name = (String) z.getValueAt(row, 1);
        String gender = (String) z.getValueAt(row, 2);
        String sal = (String) z.getValueAt(row, 3);
        String hiredate = (String) z.getValueAt(row, 4);
        String address = (String) z.getValueAt(row, 5);
        String email = (String) z.getValueAt(row, 6);
        String designation = (String) z.getValueAt(row, 7);
        String dob = (String) z.getValueAt(row, 8);
        String contact = (String) z.getValueAt(row, 9);
        String marital = (String) z.getValueAt(row, 10);
        String user = (String) z.getValueAt(row, 11);
        String pwd = (String) z.getValueAt(row, 12);

        txteid.setText(eid);       
        txtname.setText(name);
        txtcontact.setText(contact);
        txtsal.setText(sal);
        txtuser.setText(user);
        txtpwd.setText(pwd);
        txthire.setText(hiredate);
        txtadd.setText(address);
        txtemail.setText(email);
        if (marital.equalsIgnoreCase("single")) {
            rbsingle.setSelected(true);
        } else {
            rbmarried.setSelected(true);
        }

        if (gender.equalsIgnoreCase("male")) {
            rbmale.setSelected(true);
        } else {
            rbfemale.setSelected(true);
        }
        txtdob.setText(dob);
        idesignation.setSelectedItem(designation);


    }//GEN-LAST:event_tableMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        saveData();        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
        modifyData();        // TODO add your handling code here:
    }//GEN-LAST:event_modifyActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        deleteData();        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void rbmarriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmarriedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbmarriedActionPerformed

    private void txtdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdobActionPerformed

    void showData() {

        try {

            Vector h = new Vector();
            h.add("EmpId");
            h.add("Name");
            h.add("Gender");
            h.add("Salary");
            h.add("Hire Date");
            h.add("Address");
            h.add("Email");
            h.add("Designation");
            h.add("Date of Birth");
            h.add("Contact No.");
            h.add("Marital Status");
            h.add("Username");
            h.add("Password");

            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "project", "12345");
            String q = "select * from employee";
            PreparedStatement y = x.prepareStatement(q);
            ResultSet rs = y.executeQuery();

            Vector d = new Vector();

            String eid, name, gender, sal, address, email, designation, dob, contact, marital, user, pwd, hiredate;
            while (rs.next()) {
                eid = rs.getString("EmpId");
                name = rs.getString("Name");
                gender = rs.getString("Gender");
                sal = rs.getString("Salary");
                hiredate = rs.getString("Hire_Date");
                address = rs.getString("Address");
                email = rs.getString("Email");
                designation = rs.getString("Designation");
                dob = rs.getString("Date_of_Birth");
                contact = rs.getString("Contact");
                marital = rs.getString("Marital_Status");
                user = rs.getString("Username");
                pwd = rs.getString("Password");

                Vector r = new Vector();
                r.add(eid);
                r.add(name);
                r.add(gender);
                r.add(sal);
                r.add(hiredate);
                r.add(address);
                r.add(email);
                r.add(designation);
                r.add(dob);
                r.add(contact);
                r.add(marital);
                r.add(user);
                r.add(pwd);

                //inserted into data
                d.add(r);
            }
            y.close();
            x.close();

            DefaultTableModel z = new DefaultTableModel(d, h);
            table.setModel(z);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
            ex.printStackTrace();
        }

    }

    void saveData() {
        try {
            String eid, name, gender, sal, address, email, designation, dob, contact, marital, user, pwd, hiredate;
            eid = txteid.getText();
            name = txtname.getText();
            sal = txtsal.getText();
            email = txtemail.getText();
            hiredate = txthire.getText();
            contact = txtcontact.getText();

            if (rbmale.isSelected()) {
                gender = "male";
            } else {
                gender = "female";
            }
            if (rbsingle.isSelected()) {
                marital = "single";
            } else {
                marital = "married";
            }
            address = txtadd.getText();
            designation = (String) idesignation.getSelectedItem();
            dob = txtdob.getText();
            user = txtuser.getText();
            pwd = txtpwd.getText();

            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "project", "12345");

            String q = "insert into Employee values(?,?,?,?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement y = x.prepareStatement(q);

            y.setString(1, eid);
            y.setString(2, name);
            y.setString(3, sal);
            y.setString(4, designation);
            y.setString(5, hiredate);
            y.setString(6, email);
            y.setString(7, contact);
            y.setString(8, gender);
            y.setString(9, dob);
            y.setString(10, address);
            y.setString(11, marital);
            y.setString(12, user);
            y.setString(13, pwd);

            int n = y.executeUpdate();
            String d = n + " data inserted";

            y.close();

            x.close();

            JOptionPane.showMessageDialog(this, d);

            showData();
            clearData();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());

            ex.printStackTrace();
        }
    }

    void modifyData() {
        try {
            String eid, name, gender, sal, address, email, designation, dob, contact, marital, user, pwd, hiredate;
            eid = txteid.getText();
            name = txtname.getText();
            sal = txtsal.getText();
            email = txtemail.getText();
            hiredate = txthire.getText();
            contact = txtcontact.getText();

            if (rbmale.isSelected()) {
                gender = "male";
            } else {
                gender = "female";
            }
            if (rbsingle.isSelected()) {
                marital = "single";
            } else {
                marital = "married";
            }
            address = txtadd.getText();
            designation =(String) idesignation.getSelectedItem();
            dob = txtdob.getText();
            user = txtuser.getText();
            pwd = txtpwd.getText();

            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "project", "12345");

            String q = "update Employee set name=?,salary=?,gender=?,address=?,designation=?,contact=?,email=?,date_of_birth=?,marital_status=?,username=?,password=?,hire_date=? where empid=?";

            PreparedStatement y = x.prepareStatement(q);

            y.setString(13, eid);
            y.setString(1, name);
            y.setString(2, sal);
            y.setString(5, designation);
            y.setString(12, hiredate);
            y.setString(7, email);
            y.setString(6, contact);
            y.setString(3, gender);
            y.setString(8, dob);
            y.setString(4, address);
            y.setString(9, marital);
            y.setString(10, user);
            y.setString(11, pwd);

            int n = y.executeUpdate();
            String d = n + " data updated";

            y.close();

            x.close();

            JOptionPane.showMessageDialog(this, d);

            showData();
            clearData();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());

            ex.printStackTrace();
        }
    }

    void deleteData() {
        try {
            String eid;
            eid = txteid.getText();

            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "project", "12345");

            String q = "delete from employee where eid=?";

            PreparedStatement y = x.prepareStatement(q);

            y.setString(1, eid);

            int n = y.executeUpdate();
            String d = n + " data deleted";

            y.close();

            x.close();

            JOptionPane.showMessageDialog(this, d);

            showData();
            clearData();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());

            ex.printStackTrace();
        }
    }

    void clearData() {
        txteid.setText("");
        txtname.setText("");
        txtcontact.setText("");
        txtsal.setText("");
        txtuser.setText("");
        txtpwd.setText("");
        txthire.setText("");
        txtadd.setText("");
        txtemail.setText("");
        rbsingle.setSelected(true);
        rbmale.setSelected(true);
        txtdob.setText("");
        idesignation.setSelectedIndex(0);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JLabel address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel designation;
    private javax.swing.JLabel empid;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox idesignation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modify;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pwd;
    private javax.swing.JRadioButton rbfemale;
    private javax.swing.JRadioButton rbmale;
    private javax.swing.JRadioButton rbmarried;
    private javax.swing.JRadioButton rbsingle;
    private javax.swing.JLabel salary;
    private javax.swing.JButton save;
    private javax.swing.JTable table;
    private javax.swing.JTextArea txtadd;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txteid;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txthire;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpwd;
    private javax.swing.JTextField txtsal;
    private javax.swing.JTextField txtuser;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
